import { 
  Search, 
  MessageSquare, 
  Wallet, 
  User, 
  Compass, 
  Bell, 
  MoreVertical, 
  Star, 
  Send, 
  Play, 
  Lock, 
  Sparkles, 
  PlusCircle, 
  Mic, 
  ArrowRight,
  Heart,
  X,
  MapPin,
  History,
  Diamond,
  Coins,
  LogOut,
  ChevronRight,
  Settings,
  Shield,
  HelpCircle
} from 'lucide-react';

export const Icons = {
  Discover: Compass,
  Coaches: Search,
  Search: Search,
  Chat: MessageSquare,
  Wallet: Wallet,
  Profile: User,
  Notifications: Bell,
  More: MoreVertical,
  Star: Star,
  Send: Send,
  Play: Play,
  Lock: Lock,
  Sparkles: Sparkles,
  Add: PlusCircle,
  Mic: Mic,
  ArrowRight: ArrowRight,
  Heart: Heart,
  X: X,
  MapPin: MapPin,
  History: History,
  Diamond: Diamond,
  Coins: Coins,
  Logout: LogOut,
  ChevronRight: ChevronRight,
  Settings: Settings,
  Shield: Shield,
  Help: HelpCircle
};
